force-app/main/default/objects/NS_Data__c/NS_Data__c.object-meta.xml
<CustomObject>
    <label>NS Data</label>
    <nameField>
        <displayFormat>ID-{0000}</displayFormat>
        <label>NS Data ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NS Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NS_Data__c/fields/Offering__c.field-meta.xml
<CustomField>
    <fullName>Offering__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Offering</label>
    <referenceTo>Offering__c</referenceTo>
    <relationshipLabel>NS Data</relationshipLabel>
    <relationshipName>NS_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NS_Data__c/fields/School_Year__c.field-meta.xml
<CustomField>
    <fullName>School_Year__c</fullName>
    <label>School Year</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Offering__c/Offering__c.object-meta.xml
<CustomObject>
    <label>Offering</label>
    <nameField>
        <displayFormat>Of-{000}</displayFormat>
        <label>Offering ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offerings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Offering__c/fields/Campus__c.field-meta.xml
<CustomField>
    <fullName>Campus__c</fullName>
    <label>Campus</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Offering__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <label>Program</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/School_Year__c/School_Year__c.object-meta.xml
<CustomObject>
    <label>School Year</label>
    <nameField>
        <label>School Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>School Years</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/NSDataHandler.cls
public class NSDataHandler {
    public static void OfferingDataFetch(list<NS_Data__c> newlist)
    {
        set<String> sYear = new set<String>();
        set<String> camp = new set<String>();
        set<String> prog = new set<String>();
        map<string, offering__c> mapOfValuesConcatenateWiseOffering = new map<string, offering__c>();
        
        for(NS_Data__c nsData : newlist)
        {
            sYear.add(nsData.School_Year__c );
            camp.add(nsData.Campus__c );
            prog.add(nsData.Program__c);
        }
        
        if(sYear.size()>0 && camp.size()>0 && prog.size()>0)
        {
            for(Offering__c off:[select Id,School_Year__c,Campus__c,Program__c from Offering__c
                                 where School_Year__c IN:sYear and Campus__c IN:camp and
                                 Program__c IN:prog])
             {                       
              	String offeringConcatenate = off.Campus__c+'@@'+off.School_Year__c+'@@'+off.Program__c;
              	mapOfValuesConcatenateWiseOffering.put(offeringConcatenate,off);                 
             }
            
        }
            for(NS_Data__c nsData : newlist)
            {
              String nsDataConcatenate = nsData.Campus__c+'@@'+nsData.School_Year__c+'@@'+nsData.Program__c;
                if(mapOfValuesConcatenateWiseOffering.containsKey(nsDataConcatenate))
                {
                    nsData.Offering__c = mapOfValuesConcatenateWiseOffering.get(nsDataConcatenate).ID;
                    
                }
                    
            }
	}
}