force-app/main/default/objects/Grade__c/Grade__c.object-meta.xml
<CustomObject>
    <label>Grade</label>
    <nameField>
        <label>Grade Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Offeringg__c/Offeringg__c.object-meta.xml
<CustomObject>
    <label>Offeringg</label>
    <nameField>
        <label>Offering Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offeringgs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Offeringg__c/fields/Campus__c.field-meta.xml
<CustomField>
    <fullName>Campus__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campus</label>
    <referenceTo>Campus__c</referenceTo>
    <relationshipLabel>Offeringgs</relationshipLabel>
    <relationshipName>Offeringgs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Offeringg__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Offeringgs</relationshipLabel>
    <relationshipName>Offeringgs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Offeringg__c/fields/School_Year__c.field-meta.xml
<CustomField>
    <fullName>School_Year__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School Year</label>
    <referenceTo>School_Year__c</referenceTo>
    <relationshipLabel>Offeringgs</relationshipLabel>
    <relationshipName>Offeringgs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Grade__c.field-meta.xml
<CustomField>
    <fullName>Grade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grade</label>
    <referenceTo>Grade__c</referenceTo>
    <relationshipLabel>Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Time__c.field-meta.xml
<CustomField>
    <fullName>Time__c</fullName>
    <label>Time</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Time_Slot_Description__c.field-meta.xml
<CustomField>
    <fullName>Time_Slot_Description__c</fullName>
    <label>Time Slot Description</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/School_Year__c/School_Year__c.object-meta.xml
<CustomObject>
    <label>School Year</label>
    <nameField>
        <label>School Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>School Years</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/programSelectionController.cls
public class programSelectionController {
   
    @AuraEnabled
    public static list<Offeringg__c> getSchoolYear(){
         
        return [SELECT  School_Year__r.Name FROM Offeringg__c ORDER BY School_Year__r.Name ];
    } 

    @AuraEnabled
    public static list<offeringg__c> getGrade(){
         
        return [SELECT Program__r.Grade__r.Name FROM Offeringg__c ORDER BY Program__r.Grade__r.Name];
    }

    @AuraEnabled
    public static list<offeringg__c> getCampus(){
         
        return [SELECT Campus__r.Name FROM Offeringg__c Order by Campus__r.Name];
    }

    @AuraEnabled
    public static list<offeringg__c> getTime(){
        return [SELECT Program__r.Time__c , Program__r.Time_Slot_Description__c from Offeringg__c order by Program__r.Time__c ];
    }

   
    
}