force-app/main/default/objects/FrameWorkTest__c/FrameWorkTest__c.object-meta.xml
<CustomObject>
    <label>FrameWorkTest</label>
    <nameField>
        <label>FrameWorkTest Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FrameWorkTest</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FrameWorkTest__c/fields/Handler_Event__c.field-meta.xml
<CustomField>
    <fullName>Handler_Event__c</fullName>
    <label>Handler Event</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FrameWorkTest__c/fields/Handler_Ordinal__c.field-meta.xml
<CustomField>
    <fullName>Handler_Ordinal__c</fullName>
    <label>Handler Ordinal</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FrameWorkTest__c/fields/Initiating_Object__c.field-meta.xml
<CustomField>
    <fullName>Initiating_Object__c</fullName>
    <label>Initiating Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FrameWorkTest__c/fields/Iterations__c.field-meta.xml
<CustomField>
    <fullName>Iterations__c</fullName>
    <label>Iterations</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CreateFramworkTestRec.cls
public with sharing class CreateFramworkTestRec {
	
	static map<string, FrameWorkTest__c> fwtMap = new map<string, FrameWorkTest__c>();
	public FrameWorkTest__c fwt;
	static integer createOrdinal = 1;
	
	public CreateFramworkTestRec(string className, string objName, string tEvent){
		
		//checkExistingFWTRec(className, objName, tEvent);
		string mapKey = className + objName + tEvent;
		if(!fwtMap.containsKey(mapKey)){ 
			fwt = fwtMap.get(mapKey);
		}
		if(fwt == null){
			fwt = new FrameWorkTest__c();
		}
		
		fwt.name = className;
		fwt.Initiating_Object__c = objName;
		fwt.Handler_Event__c = tEvent;
		fwt.Handler_Ordinal__c = createOrdinal++;
		fwt.Iterations__c = fwt.Iterations__c == null ? 1: fwt.Iterations__c++;
		
		System.Debug(LOGGINGLEVEL.INFO,'Create FWT: ' + className + ' ' + objName + ' ' + tEvent);
		
		upsert fwt;
		
		fwtMap.put(mapKey, fwt);

	}

}